export const LOAD_PHOTOS_START = 'LOAD_PHOTOS_START';
export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS';
export const LOAD_PHOTOS_FAIL = 'LOAD_PHOTOS_FAIL';

export const LOAD_NEXT_PHOTOS_START = 'LOAD_NEXT_PHOTOS_START';
export const LOAD_NEXT_PHOTOS_SUCCESS = 'LOAD_NEXT_PHOTOS_SUCCESS';
export const LOAD_NEXT_PHOTOS_FAIL = 'LOAD_NEXT_PHOTOS_FAIL';
