export const LOAD_PHOTOS_START = 'LOAD_PHOTOS_START';
export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS';
export const LOAD_PHOTOS_FAIL = 'LOAD_PHOTOS_FAIL';

export const SET_TOKEN_START = 'SET_TOKEN_START';
export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS';
export const SET_TOKEN_FAIL = 'SET_TOKEN_FAIL';